name: Backend Deploy

on:
  push:
    paths:
      - "backapp/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 24

      - run: |
          cd backapp
          npm install
          npm run build || true

      - name: Upload to Server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          source: "backapp/*"
          target: ${{ secrets.BACK_PATH }}
          rm: true
          strip_components: 1

      - name: Restart Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          script: |
            cd ${{ secrets.BACK_PATH }}
            /home/ubuntu/.nvm/versions/node/v24.11.0/bin/npm install
            /home/ubuntu/.nvm/versions/node/v24.11.0/bin/pm2 reload app || pm2 start app.js --name app
